services:
  - type: web
    name: my-node-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ADMIN_USERNAME
        value: superadmin12
      - key: ADMIN_PASSWORD
        value: Whatsweb#
      - key: PORT
        value: 3002
